language: node_js
node_js:
- '8'
branches:
  only:
  - master
  # npm version tags
  - /^(?:[a-z-]+|@[a-z-]+\/[a-z-]+)@\d+\.\d+\.\d+$/
addons:
  firefox: latest
env:
  global:
  - DEBUG=@faltest*,faltest-helpers
  - CHROMEDRIVER_VERSION=73.0.3683.68
jobs:
  include:
  - name: Lint
    script:
    - yarn lint:git
    - yarn lint:md
    - yarn lint:js
  - name: Test
    env:
    - WEBDRIVER_HEADLESS=true
  - name: Acceptance
    services:
    - xvfb
    script:
    - yarn test:acceptance
  - name: Acceptance
    os: osx
    script:
    - yarn test:acceptance
  - name: Global Install Test
    cache:
      npm: false
    install:
    - pushd fixtures/global-install
    - yarn install --production
    - yarn link
    - popd
    script:
    - my-cli --headless
