language: node_js
node_js:
- '8'
branches:
  only:
  - master
  # npm version tags
  - /^(?:[a-z-]+|@[a-z-]+\/[a-z-]+)@\d+\.\d+\.\d+$/
addons:
  chrome: stable
  firefox: latest
jobs:
  include:
  - name: Lint
    if: type = pull_request
    script:
    - yarn lint:git
    - yarn lint:md
    - yarn lint:js
  - name: Test
    env:
    - DEBUG=remote* WEBDRIVER_HEADLESS=true
  - name: Examples
    services:
    - xvfb
    env:
    - DEBUG=remote*
    script:
    - yarn test:examples
  - name: Examples
    os: osx
    services:
    - xvfb
    env:
    - DEBUG=remote*
    script:
    - yarn test:examples
