language: node_js
node_js:
- '8'
branches:
  only:
  - master
addons:
  chrome: stable
env:
  - DEBUG=remote* WEBDRIVER_HEADLESS=TRUE
before_script:
- yarn lint:git
- yarn lint:md
- yarn lint:js
after_script:
- yarn test:examples
