language: node_js
node_js:
- '8'
branches:
  only:
  - master
  # npm version tags
  - /^(?:[a-z-]+|@[a-z-]+\/[a-z-]+)@\d+\.\d+\.\d+$/
addons:
  chrome: stable
  firefox: latest
jobs:
  include:
  - name: Lint
    script:
    - yarn lint:git
    - yarn lint:md
    - yarn lint:js
  - name: Test
    env:
    - DEBUG=remote* WEBDRIVER_HEADLESS=true
  - name: Examples
    services:
    - xvfb
    env:
    - DEBUG=remote*
    script:
    - yarn test:acceptance
  - name: Examples
    os: osx
    env:
    - DEBUG=remote*
    script:
    - yarn test:acceptance
  - name: Global Install Test
    env:
    - DEBUG=remote*
    cache:
      npm: false
    install:
    - pushd fixtures/global-install
    - yarn install --production
    - yarn link
    - popd
    script:
    - my-cli --headless
